# Day 21: Introduction to NumPy

## 1. Introduction to NumPy

NumPy (Numerical Python) is the **fundamental package for numerical computing in Python**.  
It provides:
- Support for **multi-dimensional arrays** (ndarrays).
- Efficient mathematical operations on arrays.
- Tools for linear algebra, Fourier transforms, and random number generation.
- A foundation for libraries like **Pandas, SciPy, Scikit-learn, TensorFlow, PyTorch**.

NumPy arrays are faster and more memory-efficient than Python lists because:
- They store elements of the same data type.
- They use contiguous memory blocks.
- Operations are vectorized (executed in compiled C code rather than Python loops).

## 2. Why NumPy is Essential for Numerical Computing

### Key Advantages:
- **Speed**: Array operations are optimized in C.
- **Convenience**: Easy syntax for mathematical operations.
- **Interoperability**: Works with other scientific libraries.
- **Scalability**: Handles large datasets efficiently.

In [1]:
pip install numpy

error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try brew install
    xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a Python library that isn't in Homebrew,
    use a virtual environment:
    
    python3 -m venv path/to/venv
    source path/to/venv/bin/activate
    python3 -m pip install xyz
    
    If you wish to install a Python application that isn't in Homebrew,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. You can install pipx with
    
    brew install pipx
    
    You may restore the old behavior of pip by passing
    the '--break-system-packages' flag to pip, or by adding
    'break-system-packages = true' to your pip.conf file. The latter
    will permanently disable this error.
    
    If you disable this error, we STRONGLY recommend that you additionally
    pass the '--user' flag to pip, or set 

In [4]:
# import numpy
import numpy as np

In [6]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [8]:
# 2d array
arr2 = np.array([[1,2,3] , [4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
new_arry = np.array([1,2,3]) # single array

In [11]:
new_array_1 = np.array([[10,11,12] ,[13,14,15]])
new_array_1

array([[10, 11, 12],
       [13, 14, 15]])

In [16]:
# zeros {array}
zero = np.zeros(5)
zero

array([0., 0., 0., 0., 0.])

In [17]:
# one {array}
one = np.ones(5)
one

array([1., 1., 1., 1., 1.])

In [19]:
zeros_2 = np.zeros((2,3))
zeros_2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
ones_2 = np.ones((5,10))
ones_2

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [23]:
# revise
# single array
numpy_array = np.array([1,2,3])
numpy_array

array([1, 2, 3])

In [24]:
numpy_2d = np.array([[1,2,3] , [4,5,6]])
numpy_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
# ones
one_1d = np.ones(10)
one_1d

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
one_2d = np.ones((3, 5))
one_2d

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
zeros_1d = np.zeros(5)
zeros_1d

array([0., 0., 0., 0., 0.])

In [29]:
zeros_2d = np.zeros((3,8))
zeros_2d

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [30]:
# random integers
random_integer = np.random.rand(2,4)
random_integer

array([[0.83305273, 0.52802639, 0.90830801, 0.98178634],
       [0.70307687, 0.71757924, 0.69325151, 0.89981515]])

In [31]:
random_nums = np.random.rand(4,8)
random_nums

array([[0.7509911 , 0.16901023, 0.90451313, 0.28832255, 0.85614025,
        0.8115997 , 0.23397078, 0.24457578],
       [0.43887908, 0.44781618, 0.69807255, 0.69178609, 0.16723829,
        0.34283319, 0.18043844, 0.23507322],
       [0.42271511, 0.72212537, 0.47401335, 0.32176285, 0.3636775 ,
        0.77809448, 0.04445515, 0.25703323],
       [0.23999059, 0.72940877, 0.64630957, 0.80773855, 0.58160637,
        0.86322674, 0.71742291, 0.75260893]])

## Basic Array Attributes:

- shape
- dtype
- size
- ndim

In [32]:
arr = np.array([[10,20,30] , [40,50,60]])
arr


array([[10, 20, 30],
       [40, 50, 60]])

In [33]:
arr.shape

(2, 3)

In [34]:
arr.dtype

dtype('int64')

In [35]:
arr.size

6

In [36]:
arr.ndim

2